### PR TITLE
Release UI 2.0 Android 11 Kernel sources

### PR DESCRIPTION
**Pull request by HemanthJabalpuri**
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

Issues section is disabled, since you guys can't able to bear our spam. Why we spam if you release kernel sources correctly like other good OEMs?

### CODE REVIEW

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
.
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
.
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
.
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
.
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
.
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
.
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
.
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
.
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
.
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
.
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
.
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by HemanthJabalpuri** [comment]
@realme-kernel-opensource
.
Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

**Comment by VancityJaworro** [comment]
> @realme-kernel-opensource
> .
> Please give Realme UI 2.0 Android 11 Kernel Sources and fix existing UI 1.0 Android 10 kernel sources. It is very bad to make users wasting their time to create spam like this all the time.

You're wasting your life pal :V

**Comment by HemanthJabalpuri** [comment]
> You're wasting your life pal :V

Yeah, tired of spamming

**Comment by Aston-Martinn** [comment]
@realme-kernel-opensource X7Pro kernel sources pwease!

**Comment by HemanthJabalpuri** [comment]
https://github.com/realme-kernel-opensource/realmeC12_realmeC15_AndroidR-kernel-source

**Pull request closed without merging**
